name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*' # Trigger only on version tags pushed to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0 # Updated to use .NET 9.0

      - name: Install Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release

      - name: Pack NuGet Package
        run: dotnet pack --configuration Release --output ./packages

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "packages/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
